/**
 * Curriculum plan — single source of truth for all 100 concepts across 8 modules.
 *
 * - Existing concepts (21 in DB) are included so the plan is complete.
 *   The seed:ai script skips them during concept creation but uses them for exercise top-up.
 * - exerciseTypes: authoritative array of types to reach 3 exercises each (N×3 total per concept).
 * - description: context passed to Claude when generating exercises.
 */

import type { ExerciseType, CefrLevel, GrammarFocus } from './ai-seed-config'
export type { ExerciseType, CefrLevel }
export type { GrammarFocus }

export interface ConceptPlan {
  module: string
  unit: string
  title: string
  description: string
  level: CefrLevel
  grammar_focus: GrammarFocus
  difficulty: 1 | 2 | 3 | 4 | 5
  type: string
  exerciseTypes: ExerciseType[]
}

export const CURRICULUM_PLAN: ConceptPlan[] = [
  // ─── Module 1: Connectors ────────────────────────────

  // Unit 1.1 — Concessive Connectors
  {
    module: 'Connectors',
    unit: 'Concessive Connectors',
    title: 'aunque (+ indicativo)',
    description: 'aunque followed by indicative mood to express concession when the conceded fact is real, certain, or already known to both speakers',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Connectors',
    unit: 'Concessive Connectors',
    title: 'aunque (+ subjuntivo)',
    description: 'aunque followed by subjunctive mood to concede a hypothetical, uncertain, or irrelevant condition — contrasting with the indicative use',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 3,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Concessive Connectors',
    title: 'a pesar de (que)',
    description: 'a pesar de + noun/infinitive and a pesar de que + indicative/subjunctive to introduce a strong concession, equivalent to "despite / in spite of the fact that"',
    level: 'B2',
    grammar_focus: 'both',
    difficulty: 3,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Concessive Connectors',
    title: 'por más que / por mucho que',
    description: 'por más que and por mucho que with subjunctive to express that even a maximum degree of effort or quantity does not change the outcome — "no matter how much"',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 4,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'free_write', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Concessive Connectors',
    title: 'si bien / aun cuando',
    description: 'si bien and aun cuando as formal/literary concessive connectors equivalent to "even though / although", typically used in written registers at C1 level',
    level: 'C1',
    grammar_focus: 'both',
    difficulty: 4,
    type: 'connector',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },

  // Unit 1.2 — Causal & Consecutive Connectors
  {
    module: 'Connectors',
    unit: 'Causal & Consecutive Connectors',
    title: 'puesto que / ya que',
    description: 'puesto que and ya que as formal causal connectors meaning "since / given that", used when the cause is already known or obvious to the listener',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Causal & Consecutive Connectors',
    title: 'dado que / en vista de que',
    description: 'dado que and en vista de que as formal causal connectors meaning "given that / in view of the fact that", typical of academic and administrative registers',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Causal & Consecutive Connectors',
    title: 'por lo tanto / por consiguiente',
    description: 'por lo tanto and por consiguiente as consecutive connectors meaning "therefore / consequently", used to introduce a logical result or conclusion',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Connectors',
    unit: 'Causal & Consecutive Connectors',
    title: 'de ahí que (+ subjuntivo)',
    description: 'de ahí que followed by subjunctive to introduce a consequence derived from the preceding statement — formal equivalent of "hence / that is why", always triggering subjunctive',
    level: 'C1',
    grammar_focus: 'subjunctive',
    difficulty: 5,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'Connectors',
    unit: 'Causal & Consecutive Connectors',
    title: 'tanto… que / tal… que',
    description: 'tanto/tanta/tantos/tantas… que and tal/tales… que to express a degree so high that it produces a consequence — "so much/many… that" and "such… that"',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Causal & Consecutive Connectors',
    title: 'por eso / por esa razón',
    description: 'por eso and por esa razón as high-frequency consecutive connectors meaning "that is why / for that reason", used to link a cause already mentioned to its result',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 1,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Connectors',
    unit: 'Causal & Consecutive Connectors',
    title: 'así que',
    description: 'así que as a colloquial consecutive connector meaning "so / and so", introducing a result or decision that follows from what was just said — common in spoken and informal written Spanish',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },

  // Unit 1.3 — Adversative & Contrast Connectors
  {
    module: 'Connectors',
    unit: 'Adversative & Contrast Connectors',
    title: 'sin embargo',
    description: 'sin embargo as the core adversative connector meaning "however / nevertheless", used to introduce a contrast or limitation to the preceding statement',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Adversative & Contrast Connectors',
    title: 'no obstante',
    description: 'no obstante as a formal adversative connector equivalent to sin embargo but more typical of written, academic and legal registers — "nevertheless / notwithstanding"',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Adversative & Contrast Connectors',
    title: 'en cambio / por el contrario',
    description: 'en cambio and por el contrario to introduce a contrast between two elements or situations — en cambio is more neutral, por el contrario more emphatic',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Connectors',
    unit: 'Adversative & Contrast Connectors',
    title: 'mientras que',
    description: 'mientras que to mark a contrast or opposition between two simultaneous or parallel situations — "whereas / while" in a contrastive (not temporal) sense',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Connectors',
    unit: 'Adversative & Contrast Connectors',
    title: 'ahora bien / con todo',
    description: 'ahora bien and con todo as formal adversative connectors that signal a nuanced reservation or qualification after a concession — "that said / be that as it may / all the same"',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'connector',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },

  // Unit 1.4 — Linking, Structuring & Reformulation
  {
    module: 'Connectors',
    unit: 'Linking, Structuring & Reformulation',
    title: 'en primer lugar / a continuación / por último',
    description: 'discourse sequencing markers: en primer lugar (first of all), a continuación / seguidamente (next / then), por último / finalmente (lastly / finally) — used to organise numbered points in speech and writing',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 1,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Connectors',
    unit: 'Linking, Structuring & Reformulation',
    title: 'es decir / o sea',
    description: 'es decir and o sea as reformulation markers meaning "that is to say / in other words" — es decir is neutral/formal, o sea is colloquial — used to clarify, paraphrase or specify what has just been said',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Connectors',
    unit: 'Linking, Structuring & Reformulation',
    title: 'además',
    description: 'además as the core additive connector meaning "moreover / furthermore / also", used to add a new point that supports or extends the previous one — the entry-level additive all B1 learners need',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 1,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Connectors',
    unit: 'Linking, Structuring & Reformulation',
    title: 'asimismo / del mismo modo / incluso',
    description: 'asimismo and del mismo modo as formal additive connectors ("likewise / in the same way"), and incluso as an inclusive additive meaning "even / including" — all used to add emphasis or a further supporting point',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Linking, Structuring & Reformulation',
    title: 'en cuanto a / con respecto a',
    description: 'en cuanto a and con respecto a as topic-framing connectors meaning "as for / regarding / with respect to", used to introduce a new topic or shift focus to a new aspect of the discussion',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Connectors',
    unit: 'Linking, Structuring & Reformulation',
    title: 'en definitiva / en conclusión / en suma',
    description: 'en definitiva, en conclusión and en suma as summary and conclusion markers meaning "in short / in conclusion / all in all" — used to wrap up an argument by restating the main point',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'connector',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },

  // ─── Module 2a: The Subjunctive: Core / 2b: The Subjunctive: Advanced ─────

  // Unit 2.1 — Present Subjunctive Triggers
  {
    module: 'The Subjunctive: Core',
    unit: 'Present Subjunctive Triggers',
    title: 'Verbos de deseo (querer, esperar, desear)',
    description: 'verbs of desire and wish (querer que, esperar que, desear que) that trigger the present subjunctive in the subordinate clause when the subject of the main verb differs from that of the subordinate verb',
    level: 'B1',
    grammar_focus: 'subjunctive',
    difficulty: 2,
    type: 'subjunctive_trigger',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'The Subjunctive: Core',
    unit: 'Present Subjunctive Triggers',
    title: 'Verbos de emoción (alegrarse, temer, sorprender)',
    description: 'verbs of emotion (alegrarse de que, temer que, sorprender que, encantar que, molestar que) that trigger the subjunctive — the emotional reaction is in the main clause, the cause or object is in the subjunctive clause',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 3,
    type: 'subjunctive_trigger',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'The Subjunctive: Core',
    unit: 'Present Subjunctive Triggers',
    title: 'Verbos de duda y negación (dudar, no creer, negar)',
    description: 'verbs of doubt and denial (dudar que, no creer que, negar que) that trigger subjunctive, contrasting with their affirmative forms (creer que, pensar que) which take indicative',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 3,
    type: 'subjunctive_trigger',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'The Subjunctive: Core',
    unit: 'Present Subjunctive Triggers',
    title: 'Conjunciones temporales con subjuntivo (cuando, en cuanto, hasta que)',
    description: 'temporal conjunctions (cuando, en cuanto, hasta que, tan pronto como, antes de que) that require subjunctive when referring to future or hypothetical events, but indicative when referring to habitual or past actions',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 4,
    type: 'subjunctive_trigger',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'The Subjunctive: Core',
    unit: 'Present Subjunctive Triggers',
    title: 'Conjunciones finales (para que, a fin de que)',
    description: 'final/purpose conjunctions (para que, a fin de que, con el objetivo de que) that always require subjunctive because they express a purpose or goal that has not yet been achieved',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 3,
    type: 'subjunctive_trigger',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },

  // Unit 2.2 — Imperfect Subjunctive & Hypotheticals
  {
    module: 'The Subjunctive: Advanced',
    unit: 'Imperfect Subjunctive & Hypotheticals',
    title: 'Condicional tipo 2: Si + imperfecto de subjuntivo',
    description: 'type 2 conditional: si + imperfecto de subjuntivo (si tuviera…) + condicional simple (tendría) to express hypothetical or contrary-to-fact present/future situations',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 4,
    type: 'conditional',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'The Subjunctive: Advanced',
    unit: 'Imperfect Subjunctive & Hypotheticals',
    title: 'Condicional tipo 3: Si + pluscuamperfecto de subjuntivo',
    description: 'type 3 conditional: si + pluscuamperfecto de subjuntivo (si hubiera tenido…) + condicional compuesto (habría tenido) to express counterfactual past situations — "if I had done X, I would have done Y"',
    level: 'C1',
    grammar_focus: 'subjunctive',
    difficulty: 5,
    type: 'conditional',
    exerciseTypes: ['gap_fill', 'transformation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'The Subjunctive: Advanced',
    unit: 'Imperfect Subjunctive & Hypotheticals',
    title: 'Ojalá + imperfecto de subjuntivo',
    description: 'ojalá with imperfect subjunctive to express an unlikely or impossible wish about the present or future — contrasting with ojalá + present subjunctive (likely wish) and ojalá + pluscuamperfecto (regret about past)',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 4,
    type: 'subjunctive_trigger',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'The Subjunctive: Advanced',
    unit: 'Imperfect Subjunctive & Hypotheticals',
    title: 'Imperfecto de subjuntivo en estilo indirecto',
    description: 'use of imperfect subjunctive in reported speech when the main verb is in the past tense and the original utterance contained present subjunctive — part of the sequence of tenses (concordancia de tiempos)',
    level: 'C1',
    grammar_focus: 'subjunctive',
    difficulty: 5,
    type: 'reported_speech',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },

  // Unit 2.3 — Complex Subjunctive Structures
  {
    module: 'The Subjunctive: Advanced',
    unit: 'Complex Subjunctive Structures',
    title: 'Subjuntivo con antecedente indefinido o negado',
    description: 'subjunctive in relative clauses when the antecedent is unknown, non-existent, or being sought — contrasting with indicative when the antecedent is specific and known',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 4,
    type: 'subjunctive_structure',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'The Subjunctive: Advanced',
    unit: 'Complex Subjunctive Structures',
    title: 'por + adj/adv + que (+ subjuntivo)',
    description: 'concessive structure por + adjective/adverb + que + subjunctive to express "however + adj/adv" — e.g. por difícil que sea, por mucho que insistas — a C1 structural pattern for nuanced written argumentation',
    level: 'C1',
    grammar_focus: 'subjunctive',
    difficulty: 5,
    type: 'subjunctive_structure',
    exerciseTypes: ['gap_fill', 'transformation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'The Subjunctive: Advanced',
    unit: 'Complex Subjunctive Structures',
    title: 'Secuencia de tiempos (concordancia verbal)',
    description: 'sequence of tenses (concordancia de tiempos verbales): when a subjunctive clause depends on a past-tense main verb, the correct subjunctive tense shifts from present to imperfect, and from perfect to pluperfect',
    level: 'C1',
    grammar_focus: 'both',
    difficulty: 5,
    type: 'subjunctive_structure',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'The Subjunctive: Advanced',
    unit: 'Complex Subjunctive Structures',
    title: 'que yo sepa / que yo recuerde (subjuntivo epistémico)',
    description: 'epistemic parenthetical phrases with subjunctive (que yo sepa, que yo recuerde, que yo vea) to express the speaker\'s limited certainty — "as far as I know / to my knowledge / that I can recall"',
    level: 'C1',
    grammar_focus: 'subjunctive',
    difficulty: 5,
    type: 'subjunctive_structure',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },

  // ─── Module 3: Past Tenses ────────────────────────────────────────────────

  // Unit 3.1 — Indefinido vs. Imperfecto
  {
    module: 'Past Tenses',
    unit: 'Indefinido vs. Imperfecto',
    title: 'Usos del pretérito indefinido',
    description: 'uses of pretérito indefinido (preterite): completed actions, actions with a defined time frame, sequences of events, and actions that interrupt an ongoing situation',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'past_tense',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction'],
  },
  {
    module: 'Past Tenses',
    unit: 'Indefinido vs. Imperfecto',
    title: 'Usos del pretérito imperfecto',
    description: 'uses of pretérito imperfecto: ongoing/habitual past actions, background description, simultaneous past actions, and polite requests — contrasting with indefinido for completed events',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'past_tense',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction'],
  },
  {
    module: 'Past Tenses',
    unit: 'Indefinido vs. Imperfecto',
    title: 'Indefinido vs. imperfecto: contraste narrativo',
    description: 'choosing between indefinido and imperfecto in narrative contexts — indefinido for foreground events that advance the story, imperfecto for background, description and interrupted actions',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'past_tense',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Past Tenses',
    unit: 'Indefinido vs. Imperfecto',
    title: 'Verbos con cambio de significado (saber, querer, poder, conocer)',
    description: 'verbs that change meaning depending on past tense: saber (supo = found out / sabía = knew), querer (quiso = tried / quería = wanted), poder (pudo = managed / podía = was able), conocer (conoció = met / conocía = knew)',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'past_tense',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },

  // Unit 3.2 — Perfect & Pluperfect
  {
    module: 'Past Tenses',
    unit: 'Perfect & Pluperfect',
    title: 'Pretérito perfecto vs. indefinido (uso regional y temporal)',
    description: 'choosing between pretérito perfecto (he hablado) and indefinido (hablé): in Spain, perfecto is used for past events with present relevance or within today/this week; in Latin America, indefinido replaces it almost entirely',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'past_tense',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Past Tenses',
    unit: 'Perfect & Pluperfect',
    title: 'Pretérito pluscuamperfecto: acciones anteriores al pasado',
    description: 'pretérito pluscuamperfecto (había + participio) to express an action completed before another past action or reference point — the Spanish equivalent of the past perfect "had done"',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'past_tense',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Past Tenses',
    unit: 'Perfect & Pluperfect',
    title: 'Condicional compuesto: habría + participio',
    description: 'condicional compuesto (habría + participio) to express: (1) a future action from a past perspective ("would have done"), (2) the result clause in a type-3 conditional, and (3) polite conjecture about the past',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'past_tense',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },

  // Unit 3.3 — Reported Speech
  {
    module: 'Past Tenses',
    unit: 'Reported Speech',
    title: 'Estilo indirecto: cambios de tiempo verbal',
    description: 'backshifting of tenses in reported speech when the reporting verb is in the past: presente → imperfecto, perfecto → pluscuamperfecto, futuro → condicional, presente de subjuntivo → imperfecto de subjuntivo',
    level: 'B2',
    grammar_focus: 'both',
    difficulty: 4,
    type: 'reported_speech',
    exerciseTypes: ['transformation', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Past Tenses',
    unit: 'Reported Speech',
    title: 'Estilo indirecto: expresiones de tiempo y lugar',
    description: 'changes to time and place expressions in reported speech: hoy → ese día, ayer → el día anterior, mañana → al día siguiente, aquí → allí, este → ese — adapting deictic expressions when the reporting context differs',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'reported_speech',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Past Tenses',
    unit: 'Reported Speech',
    title: 'Verbos introductores del estilo indirecto (afirmar, añadir, reconocer)',
    description: 'advanced reporting verbs beyond decir/contar: afirmar, sostener, añadir, señalar, reconocer, admitir, advertir — each carrying a nuance about the speaker\'s stance and used in formal written registers',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'reported_speech',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'Past Tenses',
    unit: 'Reported Speech',
    title: 'Estilo indirecto con imperativo → que + subjuntivo',
    description: 'converting direct imperative commands into reported speech using decir/pedir/ordenar + que + subjunctive — "She said go" → "Le dijo que fuera" — the imperative is absorbed into the subjunctive clause',
    level: 'C1',
    grammar_focus: 'subjunctive',
    difficulty: 5,
    type: 'reported_speech',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },

  // ─── Module 4: Core Spanish Contrasts ────────────────────────────────────

  // Unit 4.1 — Ser vs. Estar
  {
    module: 'Core Spanish Contrasts',
    unit: 'Ser vs. Estar',
    title: 'Ser para identidad, origen y características permanentes',
    description: 'uses of ser: identity and inherent characteristics (nationality, profession, material, ownership), origin, time/date, passive voice with ser, and objective descriptions that define what something is',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 1,
    type: 'ser_estar',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Ser vs. Estar',
    title: 'Estar para estado, ubicación y situaciones temporales',
    description: 'uses of estar: location, temporary states, ongoing actions (estar + gerundio), resultant states from a process, and conditions that can change — contrasting with ser for fixed identity',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 1,
    type: 'ser_estar',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Ser vs. Estar',
    title: 'Ser vs. estar con adjetivos (cambio de significado)',
    description: 'adjectives that change meaning depending on ser vs. estar: ser aburrido (boring personality) vs. estar aburrido (feeling bored); ser listo (clever) vs. estar listo (ready); ser malo (evil) vs. estar malo (ill)',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'ser_estar',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Ser vs. Estar',
    title: 'Ser / estar con participio: voz pasiva vs. estado resultante',
    description: 'distinguishing ser + participio (passive voice: describes an action) from estar + participio (resultant state: describes the outcome of an action) — "la puerta fue cerrada" (was closed, action) vs. "la puerta estaba cerrada" (was closed, state)',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'ser_estar',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },

  // Unit 4.2 — Por vs. Para
  {
    module: 'Core Spanish Contrasts',
    unit: 'Por vs. Para',
    title: 'Para: finalidad, destinatario y punto de llegada',
    description: 'uses of para: purpose/goal ("to do something"), recipient/destination ("for someone"), deadline ("for a date"), and movement towards a destination — para always implies a forward-looking purpose',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'por_para',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Por vs. Para',
    title: 'Por: causa, duración, intercambio y agente',
    description: 'uses of por: cause/motive ("because of"), duration ("for how long"), exchange ("in exchange for"), movement through space ("through/along"), and the agent in passive constructions',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'por_para',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Por vs. Para',
    title: 'Por vs. para: contraste en contexto',
    description: 'choosing between por and para in ambiguous or contextually similar sentences where the distinction matters — integrating cause (por) vs. purpose (para), duration (por) vs. deadline (para)',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'por_para',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Por vs. Para',
    title: 'Expresiones fijas con por y para',
    description: 'fixed idiomatic expressions with por (por fin, por supuesto, por lo menos, por las buenas, por cierto) and para (para colmo, para variar, para nada, no es para tanto) — high frequency idioms at B2+',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'por_para',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },

  // Unit 4.3 — Reflexive Verbs & Verbs of Change
  {
    module: 'Core Spanish Contrasts',
    unit: 'Reflexive Verbs & Verbs of Change',
    title: 'Verbos reflexivos vs. no reflexivos (llevar/llevarse, ir/irse)',
    description: 'pairs of verbs that change meaning with reflexive pronoun: llevar (to carry) vs. llevarse (to take away/get along), ir (to go) vs. irse (to leave), quedar (to remain) vs. quedarse (to stay)',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'reflexive',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Reflexive Verbs & Verbs of Change',
    title: 'Verbos de cambio: ponerse, quedarse, volverse, hacerse, convertirse en',
    description: 'verbs expressing change of state: ponerse + adj (temporary involuntary change), quedarse + adj (resulting state), volverse + adj (gradual change in personality), hacerse + noun/adj (intentional/gradual change), convertirse en + noun (transformation)',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'reflexive',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Reflexive Verbs & Verbs of Change',
    title: 'Construcciones con se: pasiva refleja y se impersonal',
    description: 'se + third person verb: pasiva refleja (Se venden pisos — "Flats are sold") where the subject is inanimate, vs. se impersonal (Se come bien aquí — "One eats well here") where no subject is mentioned',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'reflexive',
    exerciseTypes: ['transformation', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Reflexive Verbs & Verbs of Change',
    title: 'Verbos pseudocopulativos avanzados (resultar, parecer, seguir + adj)',
    description: 'pseudo-copulative verbs that link subject to an attribute: resultar + adj (to turn out to be), parecer + adj (to seem), seguir + adj/gerundio (to continue being/doing), llegar a ser (to eventually become) — common in formal analysis',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'reflexive',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },

  // Unit 4.4 — Temporal Adverbs & Focus Particles
  {
    module: 'Core Spanish Contrasts',
    unit: 'Temporal Adverbs & Focus Particles',
    title: 'todavía / aún vs. ya (contraste temporal afirmativo)',
    description: 'affirmative temporal contrast: todavía / aún (still — action continues) vs. ya (already / now — change has happened); core opposition that structures how Spanish marks time relative to expectations',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'adverbial',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Temporal Adverbs & Focus Particles',
    title: 'todavía no vs. ya no (contraste temporal negativo)',
    description: 'negative mirror of todavía/ya: todavía no (not yet — expected action has not happened) vs. ya no (no longer — action that was true has stopped); negation flips meaning while preserving the continuity/change axis',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'adverbial',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Core Spanish Contrasts',
    unit: 'Temporal Adverbs & Focus Particles',
    title: 'ni siquiera / siquiera (partícula de foco)',
    description: 'emphatic scalar particle: ni siquiera (not even) adds surprise or emphasis to negation, marking the lowest expected item on a scale; siquiera (even / at least) in questions, conditionals, and concessive clauses — often triggers subjunctive',
    level: 'B2',
    grammar_focus: 'both',
    difficulty: 4,
    type: 'adverbial',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },

  // ─── Module 5: Verbal Periphrases ─────────────────────────────────────────

  // Unit 5.1 — Modal Periphrases
  {
    module: 'Verbal Periphrases',
    unit: 'Modal Periphrases',
    title: 'Tener que + infinitivo (obligación personal)',
    description: 'tener que + infinitivo to express personal obligation — the subject must do something; strong and direct; contrasts with deber for moral obligation and hay que for impersonal necessity',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 1,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Modal Periphrases',
    title: 'Hay que + infinitivo (obligación impersonal)',
    description: 'hay que + infinitivo to express impersonal obligation — no specific subject; a general rule or necessity ("one must / it is necessary to") — contrasting with tener que which is personal',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 1,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Modal Periphrases',
    title: 'Deber (de) + infinitivo: obligación vs. probabilidad',
    description: 'deber + infinitivo (without de) for moral obligation ("should/ought to"), vs. deber de + infinitivo for probability/supposition ("must be / probably is") — the de marks the epistemic reading',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Modal Periphrases',
    title: 'Poder + infinitivo: capacidad, permiso y posibilidad',
    description: 'poder + infinitivo with three distinct readings: physical/mental ability ("can"), permission ("may/can I"), and possibility ("it could/might") — learners must infer the reading from context',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },

  // Unit 5.2 — Aspectual Periphrases
  {
    module: 'Verbal Periphrases',
    unit: 'Aspectual Periphrases',
    title: 'Estar + gerundio (acción en curso)',
    description: 'estar + gerundio to express an action in progress at the moment of speaking or at a specific past/future moment — the Spanish progressive, emphasising that the action is happening right now',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 1,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Aspectual Periphrases',
    title: 'Llevar + gerundio (duración acumulada)',
    description: 'llevar + time expression + gerundio to express how long an ongoing action has been continuing — "Llevo dos horas estudiando" (I have been studying for two hours); the action started in the past and continues now',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Aspectual Periphrases',
    title: 'Seguir / continuar + gerundio vs. dejar de + infinitivo',
    description: 'seguir/continuar + gerundio (to keep doing, continuative aspect) contrasted with dejar de + infinitivo (to stop doing, terminative aspect) — expressing continuation vs. cessation of an activity',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Aspectual Periphrases',
    title: 'Ir + gerundio (proceso gradual) vs. venir + gerundio (proceso anterior)',
    description: 'ir + gerundio for a gradual or progressive process unfolding over time ("Las cosas van mejorando"), vs. venir + gerundio for a process that has been developing up to the present ("Esto viene ocurriendo desde hace años")',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'periphrasis',
    exerciseTypes: ['transformation', 'translation', 'error_correction', 'listening', 'proofreading', 'register_shift'],
  },

  // Unit 5.3 — Advanced Periphrases
  {
    module: 'Verbal Periphrases',
    unit: 'Advanced Periphrases',
    title: 'Acabar de + infinitivo (recencia) vs. acabar + gerundio (resultado final)',
    description: 'acabar de + infinitivo (recent past: "to have just done") vs. acabar + gerundio (eventual outcome after a process: "to end up doing") — two very different readings of acabar',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Advanced Periphrases',
    title: 'Ponerse a / echarse a + infinitivo (inicio brusco)',
    description: 'ponerse a + infinitivo (to start doing something, often suddenly or with effort) and echarse a + infinitivo (to start suddenly and involuntarily, especially with laugh/cry/run) — both express the abrupt beginning of an action',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Advanced Periphrases',
    title: 'Volver a + infinitivo (repetición)',
    description: 'volver a + infinitivo to express the repetition of an action — equivalent to "to do something again" or "to re-do something"; the preferred Spanish structure over using "otra vez" with a simple verb',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'periphrasis',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Advanced Periphrases',
    title: 'Haber de + infinitivo: obligación formal o futuridad',
    description: 'haber de + infinitivo in formal register to express: (1) obligation with an institutional or inevitable quality ("has to / is to"), and (2) near-certain futurity in written registers — more elevated than tener que',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'periphrasis',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'Verbal Periphrases',
    unit: 'Advanced Periphrases',
    title: 'Perífrasis compuestas con subjuntivo (sin que llegue a, sin llegar a)',
    description: 'complex periphrastic constructions combining modal/aspectual periphrases with subjunctive clauses: sin que llegue a + infinitivo, antes de que llegue a + infinitivo, para que llegue a + infinitivo — expressing frustrated processes or conditions on outcomes',
    level: 'C1',
    grammar_focus: 'subjunctive',
    difficulty: 5,
    type: 'periphrasis',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },

  // ─── Module 6: Advanced Clauses ─────────────────────────────────────────

  // Unit 6.1 — Relative Clauses
  {
    module: 'Advanced Clauses',
    unit: 'Relative Clauses',
    title: 'Oraciones de relativo especificativas con que / quien / donde',
    description: 'restrictive relative clauses with que (for things and people), quien/quienes (for people after prepositions), and donde (for places) — defining or identifying the antecedent, no commas',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'relative_clause',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Relative Clauses',
    title: 'Oraciones de relativo con antecedente indefinido (+ subjuntivo)',
    description: 'relative clauses requiring subjunctive when the antecedent is unknown, non-existent, or being sought — "busco un secretario que hable chino" (I\'m looking for a secretary who speaks Chinese — don\'t know if one exists)',
    level: 'B2',
    grammar_focus: 'both',
    difficulty: 4,
    type: 'relative_clause',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Relative Clauses',
    title: 'el cual / la cual / lo cual: relativas formales y explicativas',
    description: 'el cual/la cual/los cuales/las cuales and lo cual in non-restrictive (explanatory) relative clauses, especially after prepositions — more formal than que, used to add information rather than restrict the antecedent',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'relative_clause',
    exerciseTypes: ['transformation', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Relative Clauses',
    title: 'cuyo/cuya: posesión en oraciones de relativo',
    description: 'cuyo/cuya/cuyos/cuyas as possessive relative pronoun meaning "whose" — agrees in gender and number with the noun it precedes (the thing possessed), not the antecedent; used in formal written registers',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'relative_clause',
    exerciseTypes: ['gap_fill', 'transformation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },

  // Unit 6.2 — Passive Voice
  {
    module: 'Advanced Clauses',
    unit: 'Passive Voice',
    title: 'Pasiva perifrástica: ser + participio',
    description: 'periphrastic passive: ser + past participle (+ por + agent) — the subject receives the action; participle agrees with subject in gender/number; used in formal/written registers when the action itself is the focus',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'passive',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Passive Voice',
    title: 'Pasiva refleja: se + verbo activo',
    description: 'reflexive passive: se + active verb in 3rd person (singular or plural agreeing with the grammatical subject) — typically used when no agent is mentioned; more common than ser passive in everyday spoken and written Spanish',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'passive',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Passive Voice',
    title: 'Pasiva refleja vs. perifrástica: registro y uso',
    description: 'choosing between ser + participio and se + verbo in context — ser passive is formal/literary and can name the agent; se passive is more neutral and avoids naming the agent; both are correct in formal writing but serve different communicative purposes',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'passive',
    exerciseTypes: ['transformation', 'translation', 'error_correction', 'listening', 'proofreading', 'register_shift'],
  },

  // Unit 6.3 — Advanced Adverbial Clauses
  {
    module: 'Advanced Clauses',
    unit: 'Advanced Adverbial Clauses',
    title: 'Oraciones condicionales con a menos que / con tal de que (+ subjuntivo)',
    description: 'conditional clauses with a menos que (unless) and con tal de que (as long as / provided that) — both always require subjunctive and express the condition under which the main clause is true or false',
    level: 'B2',
    grammar_focus: 'subjunctive',
    difficulty: 4,
    type: 'adverbial_clause',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Advanced Adverbial Clauses',
    title: 'Oraciones concesivas con por mucho que / aunque (indicativo vs. subjuntivo)',
    description: 'concessive adverbial clauses: por mucho que (always subjunctive) vs. aunque + indicative (known fact) vs. aunque + subjunctive (hypothetical/irrelevant) — mapping the factual/hypothetical distinction onto concessive connectors',
    level: 'B2',
    grammar_focus: 'both',
    difficulty: 4,
    type: 'adverbial_clause',
    exerciseTypes: ['gap_fill', 'transformation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Advanced Adverbial Clauses',
    title: 'Oraciones temporales con nada más / en cuanto / tan pronto como',
    description: 'temporal clauses expressing "as soon as": nada más + infinitivo (very immediate), en cuanto + subjunctive (future), tan pronto como + subjunctive (future/formal) — all expressing immediacy of sequence, with subjunctive for future events',
    level: 'B2',
    grammar_focus: 'both',
    difficulty: 3,
    type: 'adverbial_clause',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Advanced Adverbial Clauses',
    title: 'Oraciones modales: según + indicativo/subjuntivo; como si + subjuntivo',
    description: 'modal adverbial clauses: según + indicative (as/according to what is stated) vs. según + subjunctive (depending on what may be), and como si + imperfect/pluperfect subjunctive for comparisons to hypothetical situations ("as if")',
    level: 'C1',
    grammar_focus: 'both',
    difficulty: 5,
    type: 'adverbial_clause',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Advanced Adverbial Clauses',
    title: 'Oraciones consecutivas con de modo que / de forma que (+ subjuntivo/indicativo)',
    description: 'consecutive clauses with de modo que and de forma que: indicative when expressing a real result ("so that, as a result"), subjunctive when expressing a purpose or intended result ("so that, in order that") — the same connector with two different meanings',
    level: 'C1',
    grammar_focus: 'both',
    difficulty: 5,
    type: 'adverbial_clause',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'Advanced Clauses',
    unit: 'Advanced Adverbial Clauses',
    title: 'Oraciones causales negadas: no porque + subjuntivo',
    description: 'negated causal clauses: no + main clause + porque + subjunctive to deny a cause while (optionally) asserting a different one — "No lo hago porque sea fácil, sino porque es necesario"; the subjunctive in the denied cause is obligatory',
    level: 'C1',
    grammar_focus: 'subjunctive',
    difficulty: 5,
    type: 'adverbial_clause',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },

  // ─── Module 8: Conversational Spanish ──────────────────────────

  // Unit 8.1 — Fillers & Hesitation Markers (Muletillas de apoyo)
  {
    module: 'Conversational Spanish',
    unit: 'Fillers & Hesitation Markers',
    title: 'bueno (marcador conversacional)',
    description: 'bueno as a conversational marker (NOT adjective "good"): turn-opener ("Bueno, te cuento..."), hesitation filler ("Bueno... no sé"), topic shift ("Bueno, cambiando de tema"), softened disagreement ("Bueno, yo no diría eso"). All spoken registers from casual to semi-formal. Register awareness: acceptable in speech, avoid in formal writing.',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 1,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Fillers & Hesitation Markers',
    title: 'pues (marcador conversacional)',
    description: 'pues as a conversational marker: turn-taking filler ("Pues, mira..."), hesitation ("Pues... no estoy seguro"), emphasis ("¡Pues claro!"), spoken consequence ("Pues entonces vamos"). Very frequent in Peninsular Spanish. Register awareness: natural in speech at all levels, inappropriate in formal/academic writing.',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Fillers & Hesitation Markers',
    title: 'o sea (muletilla pragmática)',
    description: 'o sea as a pragmatic filler/hedge (distinct from Module 1 reformulation connector): self-correction ("Llegué tarde, o sea, no tan tarde"), approximation ("Costaba como... o sea, unos veinte euros"), hedging ("O sea, no es que no quiera..."), mild surprise ("¿O sea que ya lo sabías?"). Overuse marks very casual/youth speech. Register awareness: strictly oral, strongly informal.',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'error_correction', 'translation'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Fillers & Hesitation Markers',
    title: 'a ver',
    description: 'a ver as a conversational marker: buying thinking time ("A ver... ¿cómo te lo explico?"), introducing explanation ("A ver, el problema es que..."), expressing curiosity/anticipation ("¡A ver qué pasa!"), informal attention-caller ("A ver, escuchadme"). Register awareness: common in speech from casual to semi-formal, avoid in formal writing.',
    level: 'B1',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'transformation', 'translation'],
  },

  // Unit 8.2 — Attention-Getters & Reaction Markers (Captadores y reacciones)
  {
    module: 'Conversational Spanish',
    unit: 'Attention-Getters & Reaction Markers',
    title: 'claro / por supuesto / desde luego',
    description: 'Agreement and confirmation markers with varying formality: claro = enthusiastic agreement ("¡Claro que sí!"), hedged concession ("Claro, pero..."), sarcasm ("Claro, como siempre"). por supuesto = emphatic formal agreement. desde luego = formal emphatic certainty, sometimes expressing exasperation ("Desde luego, qué desastre"). Register awareness: claro (all registers), por supuesto (formal+neutral), desde luego (formal, sometimes ironic).',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Attention-Getters & Reaction Markers',
    title: 'mira / oye',
    description: 'Grammaticalized imperatives as attention-getters and topic-introducers: mira = draws attention to what follows ("Mira, te voy a ser sincero"), oye = calls attention / introduces request or topic change ("Oye, ¿te puedo preguntar algo?"). Both have lost literal imperative force. Register awareness: common in spoken Spanish, casual to neutral register. Oye slightly more informal than mira.',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Attention-Getters & Reaction Markers',
    title: 'hombre / mujer (marcador)',
    description: 'hombre/mujer as reaction markers (NOT gendered address): surprise ("¡Hombre, cuánto tiempo!"), protest or softened disagreement ("Hombre, eso no es justo"), reinforcement ("¡Hombre, claro que sí!"). Strongly colloquial, Peninsular Spanish. Can be used regardless of addressee gender (hombre especially). Register awareness: strictly informal spoken, inappropriate in writing or formal contexts.',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'error_correction', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Attention-Getters & Reaction Markers',
    title: 'venga / vaya / vale',
    description: 'Three high-frequency Peninsular reaction markers: venga = encouragement ("¡Venga, anímate!"), informal farewell ("Venga, hasta luego"), mild disbelief ("¡Venga ya!"). vaya = surprise/exasperation ("¡Vaya, no me lo esperaba!", "¡Vaya lío!"). vale = confirmation/agreement ("Vale, quedamos a las ocho"), conversation closer ("Vale, vale, lo entiendo"). Register awareness: all strictly oral/colloquial, very Peninsular.',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Attention-Getters & Reaction Markers',
    title: '¿no? / ¿verdad? / ¿sabes? (coletillas)',
    description: 'Tag questions (coletillas) for confirmation-seeking and listener engagement: ¿no? = most common tag ("Hace frío, ¿no?"), ¿verdad? = seeks stronger confirmation ("Es difícil, ¿verdad?"), ¿sabes? = engagement/phatic ("Es complicado, ¿sabes?"). Register awareness: ¿no? and ¿verdad? acceptable in all spoken registers, ¿sabes? more informal and can be overused.',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 2,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },

  // Unit 8.3 — Hedges, Justifiers & Emphatic Markers (Atenuadores y enfatizadores)
  {
    module: 'Conversational Spanish',
    unit: 'Hedges, Justifiers & Emphatic Markers',
    title: 'es que',
    description: 'es que as a justification/excuse marker: "The thing is..." ("Es que no tuve tiempo"), "It\'s just that..." ("Es que me da vergüenza"). Very high frequency in spoken Spanish. Often introduces explanations that function as excuses or mitigating reasons. Register awareness: natural in speech from casual to semi-formal, avoid in formal/academic writing. Overuse can sound defensive.',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Hedges, Justifiers & Emphatic Markers',
    title: 'de hecho (registro oral)',
    description: 'de hecho as an emphatic "actually/in fact" in spoken discourse: corrects misconceptions ("De hecho, no fue así"), strengthens assertions ("De hecho, es el mejor de todos"), introduces surprising information ("De hecho, ya lo sabía"). Register awareness: acceptable in semi-formal and formal speech/writing (unlike most markers in this module), but in spoken use often carries more emphatic force than in writing.',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'translation', 'error_correction', 'listening', 'proofreading'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Hedges, Justifiers & Emphatic Markers',
    title: 'eso sí',
    description: 'eso sí as a concessive-adversative marker meaning "mind you / that said / though": introduces a caveat or exception after a positive or neutral statement ("La comida estaba buena; eso sí, el servicio fue lento", "Puedes ir, eso sí, llega antes de las diez"). Register awareness: common in spoken Spanish, also acceptable in informal writing. Requires preceding context to function.',
    level: 'B2',
    grammar_focus: 'indicative',
    difficulty: 3,
    type: 'pragmatic_marker',
    exerciseTypes: ['gap_fill', 'transformation', 'translation', 'listening', 'proofreading'],
  },

  // Unit 8.4 — Advanced Colloquial Markers & Register Switching (Marcadores coloquiales avanzados)
  {
    module: 'Conversational Spanish',
    unit: 'Advanced Colloquial Markers & Register Switching',
    title: 'en plan / tipo (atenuadores coloquiales)',
    description: 'en plan and tipo as youth hedges for approximation and vagueness: en plan = "like, sort of" ("Estaba en plan borde", "Lo dijo en plan broma"), tipo = "like, kind of" ("Era tipo una fiesta pero no"). Both are strongly informal and generationally marked (youth/millennial Spanish). Key skill: knowing WHEN NOT to use these — inappropriate in formal, professional, or academic contexts. Register awareness: strictly informal/colloquial, avoid in writing.',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'pragmatic_marker',
    exerciseTypes: ['transformation', 'error_correction', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Advanced Colloquial Markers & Register Switching',
    title: 'total (que) / vamos (marcador)',
    description: 'total (que) as a spoken summariser: "long story short / basically" ("Total, que al final no fuimos"). vamos as an emphatic self-correction or intensifier: "I mean" ("Es caro, vamos, carísimo"), "come on" ("¡Vamos, que podemos!"). Both are oral-only markers. Register awareness: strictly colloquial spoken Spanish, never in formal/academic writing. vamos (marker) is distinct from vamos (verb "we go").',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'pragmatic_marker',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
  {
    module: 'Conversational Spanish',
    unit: 'Advanced Colloquial Markers & Register Switching',
    title: 'entonces (marcador oral) / o sea que',
    description: 'entonces as a spoken transition/consequence marker beyond its textbook meaning: topic transition ("Entonces, ¿qué hacemos?"), drawing conclusions ("Entonces no te gustó"), narrative sequencing ("Y entonces llegó ella"). o sea que as a colloquial consequence marker: "so basically" ("O sea que no vienes, ¿no?"). Register awareness: entonces is versatile across registers but its discourse-marker uses are oral; o sea que is strictly colloquial.',
    level: 'C1',
    grammar_focus: 'indicative',
    difficulty: 4,
    type: 'pragmatic_marker',
    exerciseTypes: ['transformation', 'translation', 'free_write', 'listening', 'proofreading', 'register_shift'],
  },
]
