/**
 * pnpm seed:vocab:apply [--dry-run] <path-to-vocab-sentences-YYYY-MM-DD.json>
 *
 * Reads the JSON generated by pnpm seed:vocab and inserts vocab_sentences rows.
 * Idempotent: skips sentences for items that already have sentences in DB.
 */

import fs from 'fs'
import { createClient } from '@supabase/supabase-js'
import type { Database } from '../supabase/types'

// ── Environment ──────────────────────────────────────────────────────────────

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing required env vars: NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}

const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY)

// ── Types ─────────────────────────────────────────────────────────────────────

type SentenceEntry = {
  sentence: string
  correct_form: string
  answer_variants: string[] | null
  english: string
  hint: string
}

type ItemResult = {
  expression: string
  vocab_id: string
  category: string
  sentences: SentenceEntry[]
}

type OutputFile = {
  generated_at: string
  items: ItemResult[]
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2)
  const dryRun = args.includes('--dry-run')
  const filePath = args.find((a) => !a.startsWith('--'))

  if (!filePath) {
    console.error('Usage: pnpm seed:vocab:apply [--dry-run] <path-to-vocab-sentences-YYYY-MM-DD.json>')
    process.exit(1)
  }

  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`)
    process.exit(1)
  }

  const data = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as OutputFile

  console.log(`File: ${filePath}`)
  console.log(`Generated at: ${data.generated_at}`)
  console.log(`Items: ${data.items.length}`)
  if (dryRun) console.log('DRY RUN — no rows will be inserted\n')

  let totalSentences = 0
  for (const item of data.items) {
    totalSentences += item.sentences.length
  }
  console.log(`Total sentences to insert: ${totalSentences}`)

  // Check which vocab_ids already have sentences
  const vocabIds = data.items.map((i) => i.vocab_id)
  const { data: existingRows, error: fetchErr } = await supabase
    .from('vocab_sentences')
    .select('vocab_id')
    .in('vocab_id', vocabIds)

  if (fetchErr) {
    console.error('Failed to fetch existing sentences:', fetchErr.message)
    process.exit(1)
  }

  const existingVocabIds = new Set(
    (existingRows as Array<{ vocab_id: string }> ?? []).map((r) => r.vocab_id)
  )

  let inserted = 0
  let skippedItems = 0

  for (const item of data.items) {
    if (existingVocabIds.has(item.vocab_id)) {
      skippedItems++
      continue
    }

    if (dryRun) {
      console.log(`  [DRY] Would insert ${item.sentences.length} sentences for "${item.expression}"`)
      inserted += item.sentences.length
      continue
    }

    const rows = item.sentences.map((s) => ({
      vocab_id: item.vocab_id,
      sentence: s.sentence,
      correct_form: s.correct_form,
      answer_variants: s.answer_variants,
      english: s.english,
      hint: s.hint,
    }))

    const { error: insertErr } = await supabase
      .from('vocab_sentences')
      .insert(rows)

    if (insertErr) {
      console.error(`  ✗ Error inserting for "${item.expression}":`, insertErr.message)
      continue
    }

    inserted += rows.length
    console.log(`  ✓ ${item.expression} → ${rows.length} sentences`)
  }

  console.log(`\nDone! Inserted: ${inserted}, Skipped (already in DB): ${skippedItems}`)
}

main().catch(console.error)
