/**
 * pnpm seed:conjugations:apply [--dry-run] <path-to-verb-conjugations-YYYY-MM-DD.json>
 *
 * Reads the JSON generated by pnpm seed:conjugations and upserts rows into
 * verb_conjugations. Idempotent via ON CONFLICT DO UPDATE (primary key is verb_id + tense).
 *
 * Safe to re-run — will update existing rows if conjugations changed.
 */

import fs from 'fs'
import { createClient } from '@supabase/supabase-js'
import type { Database } from '../supabase/types'

// ── Environment ──────────────────────────────────────────────────────────────

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing required env vars: NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}

const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY)

// ── Types ─────────────────────────────────────────────────────────────────────

type ConjugationEntry = {
  stem: string
  yo: string
  tu: string
  el: string
  nosotros: string
  vosotros: string
  ellos: string
}

type ComboResult = {
  verb_infinitive: string
  verb_id: string
  tense: string
  conjugations: ConjugationEntry
}

type OutputFile = {
  generated_at: string
  combos: ComboResult[]
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2)
  const dryRun = args.includes('--dry-run')
  const filePath = args.find((a) => !a.startsWith('--'))

  if (!filePath) {
    console.error('Usage: pnpm seed:conjugations:apply [--dry-run] <path-to-verb-conjugations-YYYY-MM-DD.json>')
    process.exit(1)
  }

  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`)
    process.exit(1)
  }

  const data = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as OutputFile

  console.log(`File: ${filePath}`)
  console.log(`Generated at: ${data.generated_at}`)
  console.log(`Combos to upsert: ${data.combos.length}`)

  if (dryRun) {
    console.log('\n[DRY RUN] No changes made.')
    return
  }

  const rows = data.combos.map((c) => ({
    verb_id:  c.verb_id,
    tense:    c.tense,
    stem:     c.conjugations.stem,
    yo:       c.conjugations.yo,
    tu:       c.conjugations.tu,
    el:       c.conjugations.el,
    nosotros: c.conjugations.nosotros,
    vosotros: c.conjugations.vosotros,
    ellos:    c.conjugations.ellos,
  }))

  let upserted = 0
  const BATCH_SIZE = 50

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE)
    const { error } = await supabase
      .from('verb_conjugations')
      .upsert(batch, { onConflict: 'verb_id,tense' })

    if (error) {
      console.error(`Error upserting batch ${Math.floor(i / BATCH_SIZE) + 1}:`, error)
      process.exit(1)
    }
    upserted += batch.length
    console.log(`Upserted ${upserted} / ${rows.length} rows`)
  }

  console.log(`\n✓ Done. ${upserted} verb_conjugations rows upserted.`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
