/**
 * pnpm seed:verbs:apply [--dry-run] <path-to-verb-sentences-YYYY-MM-DD.json>
 *
 * Reads the JSON generated by pnpm seed:verbs and inserts verb_sentences rows.
 * Safe to run with --dry-run first to preview counts.
 *
 * Idempotent: skips combos (verb_id + tense) that already have sentences in DB.
 */

import fs from 'fs'
import { createClient } from '@supabase/supabase-js'
import type { Database } from '../supabase/types'

// ── Environment ──────────────────────────────────────────────────────────────

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing required env vars: NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY')
  process.exit(1)
}

const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY)

// ── Types ─────────────────────────────────────────────────────────────────────

type SentenceEntry = {
  pronoun: string
  sentence: string
  correct_form: string
  tense_rule: string
}

type ComboResult = {
  verb_infinitive: string
  verb_id: string
  tense: string
  sentences: SentenceEntry[]
}

type OutputFile = {
  generated_at: string
  combos: ComboResult[]
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2)
  const dryRun = args.includes('--dry-run')
  const filePath = args.find((a) => !a.startsWith('--'))

  if (!filePath) {
    console.error('Usage: pnpm seed:verbs:apply [--dry-run] <path-to-verb-sentences-YYYY-MM-DD.json>')
    process.exit(1)
  }

  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`)
    process.exit(1)
  }

  const data = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as OutputFile

  console.log(`File: ${filePath}`)
  console.log(`Generated at: ${data.generated_at}`)
  console.log(`Combos: ${data.combos.length}`)

  let totalSentences = 0
  for (const combo of data.combos) {
    totalSentences += combo.sentences.length
  }
  console.log(`Total sentences to insert: ${totalSentences}`)

  // Dedup: fetch existing (verb_id, tense) combos from DB
  const { data: existingRows, error: fetchErr } = await supabase
    .from('verb_sentences')
    .select('verb_id, tense')

  if (fetchErr) {
    console.error('Error fetching existing verb_sentences:', fetchErr)
    process.exit(1)
  }

  const existingCombos = new Set(
    ((existingRows as Array<{ verb_id: string; tense: string }>) ?? []).map(
      (r) => `${r.verb_id}::${r.tense}`,
    ),
  )

  const newCombos = data.combos.filter(
    (combo) => !existingCombos.has(`${combo.verb_id}::${combo.tense}`),
  )
  const skippedCombos = data.combos.length - newCombos.length

  if (skippedCombos > 0) {
    console.log(`⚠️  Skipped ${skippedCombos} combo(s) already in DB`)
  }

  let newSentenceCount = 0
  for (const combo of newCombos) {
    newSentenceCount += combo.sentences.length
  }
  console.log(`Sentences to insert: ${newSentenceCount}`)

  if (dryRun) {
    console.log('\n[DRY RUN] No changes made.')
    return
  }

  if (newCombos.length === 0) {
    console.log('\n✓ Nothing to insert — all combos already exist.')
    return
  }

  // Insert in batches of 50 rows
  const rows: Array<{
    verb_id: string
    tense: string
    pronoun: string
    sentence: string
    correct_form: string
    tense_rule: string
  }> = []

  for (const combo of newCombos) {
    for (const s of combo.sentences) {
      rows.push({
        verb_id:      combo.verb_id,
        tense:        combo.tense,
        pronoun:      s.pronoun,
        sentence:     s.sentence,
        correct_form: s.correct_form,
        tense_rule:   s.tense_rule,
      })
    }
  }

  let inserted = 0
  const BATCH_SIZE = 50

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE)
    const { error } = await supabase.from('verb_sentences').insert(batch)
    if (error) {
      console.error(`Error inserting batch ${i / BATCH_SIZE + 1}:`, error)
      process.exit(1)
    }
    inserted += batch.length
    console.log(`Inserted ${inserted} / ${rows.length} sentences`)
  }

  console.log(`\n✓ Done. ${inserted} verb_sentences rows inserted.`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
